# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MikataUIv2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1260, 670)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 1260, 670))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("Resources/Images/Background.png"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.MIKATA = QtWidgets.QLabel(self.centralwidget)
        self.MIKATA.setGeometry(QtCore.QRect(210, 260, 410, 70))
        self.MIKATA.setText("")
        self.MIKATA.setPixmap(QtGui.QPixmap("Resources/Images/MIKATA.png"))
        self.MIKATA.setObjectName("MIKATA")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(850, 120, 350, 440))
        self.groupBox.setStyleSheet("QGroupBox {\n"
"border : 2px solid rgb(29, 186, 255);\n"
"border-radius : 10px;\n"
"background-color: rgba(0, 0, 0, 128);\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.chatbox = QtWidgets.QPlainTextEdit(self.groupBox)
        self.chatbox.setGeometry(QtCore.QRect(0, 0, 350, 390))
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        self.chatbox.setFont(font)
        self.chatbox.setStyleSheet("border : 0px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(0,0,0,10);\n"
"QScrollBar: {\n"
" border : 2px solid red; background : black; width :15px ;\n"
" }\n"
"QScrollBar::handle:vertical {\n"
" background : black; min-height : 30px; \n"
"}")
        self.chatbox.setReadOnly(True)
        self.chatbox.setObjectName("chatbox")
        self.command = QtWidgets.QLineEdit(self.groupBox)
        self.command.setGeometry(QtCore.QRect(5, 397, 340, 35))
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        self.command.setFont(font)
        self.command.setStyleSheet("background-color: rgba(0, 0, 0, 64);\n"
"border : 2px solid rgb(0, 174, 218);\n"
"border-radius : 10px;\n"
"color : white;\n"
"padding-right: 30px;")
        self.command.setText("")
        self.command.setObjectName("command")
        self.snd_button = QtWidgets.QPushButton(self.groupBox)
        self.snd_button.setGeometry(QtCore.QRect(310, 400, 30, 30))
        self.snd_button.setStyleSheet("background-color: transparent;")
        self.snd_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resources/Images/Send Button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.snd_button.setIcon(icon)
        self.snd_button.setIconSize(QtCore.QSize(25, 25))
        self.snd_button.setObjectName("snd_button")
        self.prev_button = QtWidgets.QPushButton(self.centralwidget)
        self.prev_button.setGeometry(QtCore.QRect(260, 500, 80, 40))
        self.prev_button.setStyleSheet("background-color: transparent;")
        self.prev_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Resources/Images/Previous Button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prev_button.setIcon(icon1)
        self.prev_button.setIconSize(QtCore.QSize(70, 45))
        self.prev_button.setObjectName("prev_button")
        self.play_button = QtWidgets.QPushButton(self.centralwidget)
        self.play_button.setGeometry(QtCore.QRect(390, 500, 40, 40))
        self.play_button.setStyleSheet("background-color: transparent;")
        self.play_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Resources/Images/Platy Button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_button.setIcon(icon2)
        self.play_button.setIconSize(QtCore.QSize(35, 35))
        self.play_button.setObjectName("play_button")
        self.next_button = QtWidgets.QPushButton(self.centralwidget)
        self.next_button.setGeometry(QtCore.QRect(480, 500, 80, 40))
        self.next_button.setStyleSheet("background-color: transparent;")
        self.next_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Resources/Images/Next Button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next_button.setIcon(icon3)
        self.next_button.setIconSize(QtCore.QSize(70, 45))
        self.next_button.setObjectName("next_button")
        self.pause_button = QtWidgets.QPushButton(self.centralwidget)
        self.pause_button.setGeometry(QtCore.QRect(390, 500, 40, 40))
        self.pause_button.setStyleSheet("background-color: transparent;")
        self.pause_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Resources/Images/Pause Button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pause_button.setIcon(icon4)
        self.pause_button.setIconSize(QtCore.QSize(40, 40))
        self.pause_button.setObjectName("pause_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
